Vagrant.configure("2") do |config|

  # Define the first VM (k3s server)
  config.vm.define "vchizhovS" do |control|
    control.vm.box = "debian/bookworm64"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.memory = "1024"
      v.cpus = 1
      v.name = "vchizhovS"
    end

    control.vm.hostname = "vchizhovS"

    control.vm.provision "shell", inline: <<-SCRIPT
      apt-get update -y
      echo Installation of k3s server
      apt-get install curl -y
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --flannel-backend none --token 12345
    SCRIPT
  end
end
