Vagrant.configure("2") do |config|

  # Define the first VM (k3s server)
  config.vm.define "vchizhovS" do |control|
    control.vm.box = "debian/bookworm64"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.memory = "2048"
      v.cpus = 2
      v.name = "vchizhovS"
    end

    control.vm.hostname = "vchizhovS"
	control.vm.provision "shell", path: "scripts/master.sh"
  end
end
