Vagrant.configure("2") do |config|

  # Define the first VM (k3s server)
  config.vm.define "vchizhovS" do |control|
    control.vm.box = "debian/bookworm64"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.memory = "1024"
      v.cpus = 1
      v.name = "vchizhovS"
    end

    control.vm.hostname = "vchizhovS"
    control.vm.provision "shell", path: "script/master.sh"

  end

  # Define the second VM (k3s agent)
  config.vm.define "vchizhovSW" do |control|
    control.vm.box = "debian/bookworm64"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |v|
      v.memory = "1024"
      v.cpus = 1
      v.name = "vchizhovSW"
    end

    control.vm.hostname = "vchizhovSW"
    control.vm.provision "shell", path: "script/agent.sh"
  end
end

