Vagrant.configure("2") do |config|

  config.vm.define "vchizhovS" do |control|
	control.vm.box = "debian/bookworm64"
	control.vm.network "private_network", ip: "192.168.56.110"	
	control.vm.provider "virtualbox" do |v|
		v.memory = "512"    
		v.cpus = 1
		v.name = "vchizhovS"
	end
	
	control.vm.hostname = "vchizhovS"
  end

end

